data: data/stories/STORIES_BPE
save_checkpoint_steps: 2000
keep_checkpoint: 10
seed: 123
warmup_steps: 4000
train_steps: 60000
valid_steps: 500
report_every: 50

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
enc_layers: 6
dec_layers: 6
transformer_ff: 2048
heads: 8

accum_count: 43
optim: adam
adam_beta1: 0.9
adam_beta2: 0.98
decay_method: invsq
learning_rate: 0.0005
warmup_init_factor: 5000
max_grad_norm: 0.0

batch_size: 2600
valid_batch_size: 4
batch_type: tokens
normalization: tokens
dropout: 0.3
attn_dropout: 0.2
label_smoothing: 0.1

max_generator_batches: 0
force_bs1: 'true'

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'
position_encoding_ctxsize: 1024
share_decoder_embeddings: 'true'
share_embeddings: 'true' # This is not quite the same, but probably should only have positive effect?

# world_size must be according to the number of GPU's used.
world_size: 1
# Setting CPU by default, Not everyone has GPU. For GPU uncomment the following lines
#gpu_ranks: 
#- 0
#- 1
#- 2
#- 3
tensorboard: 'true'
